"use client";

import Head from "next/head";
import { Poppins } from "next/font/google";
import { GlobalStyle } from "../config/globalStyles";
import { QueryClient, QueryClientProvider } from "react-query";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

const queryClient = new QueryClient();

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <QueryClientProvider client={queryClient}>
        <GlobalStyle />
        <body className={poppins.className}>{children}</body>
      </QueryClientProvider>
    </html>
  );
}
